version: '3.8'

services:
  frontend-service:
    build: ./frontend
    container_name: frontend-service
    networks:
      - nfpreview-network
    expose:
      - "80"

  backend-service:
    build: ./backend
    container_name: backend-service
    networks:
      - nfpreview-network
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1

  nginx-service:
    build: ./nginx
    container_name: nginx-service
    depends_on:
      - frontend-service
      - backend-service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/hostpreview.space/fullchain.pem:/etc/nginx/ssl/nginx.crt:ro
      - /etc/letsencrypt/live/hostpreview.space/privkey.pem:/etc/nginx/ssl/nginx.key:ro
    networks:
      - nfpreview-network
    restart: unless-stopped

networks:
  nfpreview-network:
    driver: bridge
